apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
      - name: your-container
        image: gcr.io/your-gcp-project/your-app:latest
        ports:
        - containerPort: 80

